name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Update project from git
        run: |
          ssh root@81.163.29.23 "cd /var/www/php/app/ && sudo -u www-data git pull"
      - name: Init the app
        run: |
          ssh $SSH_USERNAME@$SSH_HOST "cd /var/www/php/app/ && composer install --no-interaction --prefer-dist --optimize-autoloader && php artisan migrate --force && php artisan db:seed --force && npm ci && npm run build"
        env:
         SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
         SSH_HOST: ${{ secrets.SSH_HOST }}
